name: Tests
on:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --out-format=colored-line-number
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.*'
      - run: go generate ./...
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
          (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)
  test:
    name: Terraform Provider Acceptance Tests
    needs: build
    runs-on: ubuntu-latest-16-cores
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - '1.4.*'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - name: Run acceptance tests
        run: go test -v -cover -timeout 180m ./...
        env:
          TF_ACC: "1"
          MARQO_HOST: ${{ secrets.MARQO_HOST }}
          MARQO_API_KEY: ${{ secrets.MARQO_API_KEY }}
        timeout-minutes: 180
